import 'dart:convert';

/// Encodes an arbitrary Dart value as a string for transport to the DevTools UI.
///
/// The UI's value panel attempts to JSON-decode the result. When the decode
/// succeeds and produces a [Map] or [List], the value is rendered as a
/// structured JSON tree; otherwise the raw string is shown.
///
/// Behaviour by value type:
///
/// - `null` → returns `null` (the UI shows "No value yet").
/// - Built-in JSON types (`num`, `bool`, `String`, `Map`, `List` of these)
///   → encoded natively by `jsonEncode`. Nested maps and lists serialize
///   recursively.
/// - Custom classes with a `toJson()` method → `jsonEncode` invokes it.
///   This includes classes generated by `json_serializable`, `freezed`, or
///   hand-written ones.
/// - Anything else (including classes without `toJson()`, [DateTime],
///   [Uri], etc.) → falls back to `toString()`. The fallback only applies
///   at the leaf where serialization can't continue: a `Map<String, User>`
///   where `User` has no `toJson()` still serializes the map structure,
///   with each `User` rendered as the result of `User.toString()`.
///
/// Returning `null` for a `null` input is intentional: the UI distinguishes
/// "value never emitted" (null result) from "value emitted but unrenderable".
String? encodeValue(Object? value) {
  if (value == null) return null;
  return jsonEncode(value, toEncodable: (nonEncodable) => nonEncodable.toString());
}
